In [ ]:
#################################################################
#   Example:  Numpy array initialization
#
#             There are various ways to initialize a Numpy array.
#             Several examples are shown below.

import numpy as np

#Array dimensions for use later
nx = 10
ny = 20

#1-D array, 8-byte real, using np.empty means that
# values are not initialized to anything (in particular...)
earr = np.empty(nx,dtype='float64')
print('earr: ', earr)
print(' ')

#1-D array, 4-byte real, using np.zeros
# means that values are initialized to zero
zarr = np.zeros(nx,dtype='float32')
print('zarr: ', zarr)
print(' ')


#2-d array, 4-byte integer, values set to zero
# Row-major ordering (second index is fastest; like C/C++)
iarr2da = np.zeros((nx,ny),dtype='int32')
print('iarr2da: ')
print(iarr2da)
print(' ')

#2-d array, 4-byte integer, values set to zero
#Column-major ordering (first index is fastest; like Fortran)
iarr2db = np.zeros((nx,ny),dtype='int32', order ='F')
print('iarr2db: ') 
print(iarr2db)
print(' ')


#1-d array, 4-byte real, values spaced  with integer spacing 
# in the range [istart,iend], with stepsize istep
# This is accomplished via np.arange
istart = 10
iend = 20
istep = 2
arrsp = np.arange(istart,iend,istep,dtype='float32')
print('arrsp: ', arrsp)
print(' ')

#1-d array, 8-byte real, values spaced with non-integer spacing
# in the range [istart,iend], with stepsize = (iend-istart)/nstep
istart = 100
iend = 200
nstep = 200
arrsp2 = np.linspace(istart,iend,nstep,dtype='float64')
print('arrsp2: ')
print(arrsp2)
print(' ')


# 1-d array, 8-byte real, initialized using values from an existing list
oned = [0,1.2, 5.6, 8.9]
arrinit = np.array(oned,dtype='float64')
print('arrinit: ', arrinit)
print(' ')

# 2-d array, 4-byte integer, initialized using values from existing 2-D list
twod = [ [ 1, 2], [3,4] ]
arrinit2d = np.array(twod,dtype='float64')
print('arrinit2d: ')
print(arrinit2d)
print(' ')

array_names = ['zarr', 'earr', 'iarr2da', 'iarr2db','arrsp', 'arrsp2', 'arrinit', 'arrinit2d']
arrays = [zarr,earr,iarr2da,iarr2db, arrsp, arrsp2, arrinit, arrinit2d]

for i,o in enumerate(arrays):
    ndim = o.ndim
    dtype = o.dtype
    isize = o.itemsize
    ssp = o.nbytes
    ne = o.size
    print('////////////////////////////////////////')
    print(' Information for ndarray '+array_names[i])
    print(' data type            : ', dtype)
    print(' number of elements   : ', ne)
    print(' element size (bytes) : ', isize)
    print(' dimensions           : ', ndim)
    for j in range(ndim):
        print('     dimension '+str(j)+' size :', o.shape[j])
    print(' storage space (bytes): ', ssp)
    if (ndim > 1):
        print(' Element spacing along dimension 1 (bytes): ', o.strides[0])
        print(' Element spacing along dimension 2 (bytes): ', o.strides[1])
    print('')


In [ ]:
int3 = np.zeros(3,'int16')

In [ ]:
print(int3)

In [ ]:
lsp = np.linspace(0,.3,4,dtype='d')

In [ ]:
print(lsp.itemsize)

In [ ]:
my_list = [1.0, .1, 9.5, 11]
my_arr = np.array(my_list,dtype='float64')

In [ ]:
print(my_arr)

In [ ]:
in16 = np.zeros(3,'int16')

In [ ]:
print(in16.itemsize)

In [ ]:
###############################################################################
#   Example:   Using Numpy arrays instead lists
#
#              Using numpy array syntax can speed up a calculation considerably.
#              We illustrate this by recording the time needed to perform
#              a = a*2 and c = a*b for lists and Numpy arrays with large
#              element counts.

import numpy as np
import time

npts = 10000000    # number of elements in each list/array
ntrials = 2        # number of times to repeat the calculation

#Initialize our Numpy arrays
a = np.zeros(npts,dtype='d')
b = np.zeros(npts,dtype='d')

#Initialize our lists
d = []
e = []
f = []
for i in range(npts):
    d.append(0.1)
    e.append(2.0)
    f.append(0.0)

print(' ')
print('Timing array vs. list operations for arrays having '+str(npts)+' elements...')

t0 = time.time()
a = a*2
t1 = time.time()
dt1 = t1-t0


t0 = time.time()
c = a*b
t1 = time.time()
dt2 = t1-t0

tstr = '{:.4e}'.format(dt1)
tstr2 = '{:.4e}'.format(dt2)
print('')
print('Time to compute a=a*2 using numpy array syntax: '+tstr+' seconds')
print('Time to compute c=a*b using numpy array syntax: '+tstr2+' seconds')


t0 = time.time()
for j in range(npts):
    d[j] = d[j]*2
t1 = time.time()
dt3 = t1-t0

t0 = time.time()
for j in range(npts):
    f[j] = d[j]*e[j]
t1 = time.time()
dt4 = t1-t0

tstr3 = '{:.4e}'.format(dt3)
tstr4 = '{:.4e}'.format(dt4)
print('')
print('Time to compute a=a*2 using lists: '+tstr3+' seconds')
print('Time to compute c=a*b using lists: '+tstr4+' seconds')

In [ ]:
########################################################################
#   Example:   Array syntax vs. explicit looping
#
#              Since Python is an interpretted language, explicit
#              loops are inherently slow.  It is often advantageous
#              to rewrite loops using array syntax.  This allows 
#              Python to use more efficient routines, compiled 
#              & optimized in a lower-level language (like C) where possible.
#              
#              In this example, we record the time to calculate a=a*2 and
#              c = a*b using both array syntax and explicit looping.

import numpy as np
import time

npts = 1000000
ntrials = 2
a = np.zeros(npts)
b = np.zeros(npts)


print(' ')
print('   Timing array operations vs. explicit looping')
print('   Number of elements: ', npts)
print('   Number of trials  : ', ntrials)
print(' ')

t0 = time.time()
for i in range(ntrials):
    a *= 2
t1 = time.time()
dt1 = t1-t0


t0 = time.time()
for i in range(ntrials):
    for j in range(npts):
        a[j] *= 2
t1 = time.time()
dt2 = t1-t0


t0 = time.time()
for i in range(ntrials):
    c = a*b
t1 = time.time()
dt3 = t1-t0



t0 = time.time()
for i in range(ntrials):
    for j in range(npts):
            c[j] = a[j]*b[j]
t1 = time.time()
dt4 = t1-t0

tstr1 = '{:.4e}'.format(dt1)
tstr2 = '{:.4e}'.format(dt2)
tstr3 = '{:.4e}'.format(dt3)
tstr4 = '{:.4e}'.format(dt4)

print('   In-place, Array op (a *=2)                   : '+tstr1+' seconds')
print('   In-place, explicit loop (a[j] *=2)           : '+tstr2+' seconds')
print('   Array Mult: array op ( c = a*b )             : '+tstr3+' seconds')
print('   Array Mult: explicit loop (c[j] = a[j]*b[j]) : '+tstr4+' seconds')

    




In [ ]:
#//////////////////////////////////////////////////////////////
#                   Exercise 1:
# Rewrite the following program using numpy arrays and 
# array operations where possible (instead of explicit loops).
import time
import numpy as np
n = 1000000  

t1 = time.time()
c = np.arange(1,n+1,1,dtype='i')
a = 4*c
b = c*c

print(a.shape)
print(b.shape)

t2 = time.time()

dsum = 0.0
e = a*b
dsum = np.sum(e)
#dsum = np.dot(a,b)
#for i in range(n):
#    dsum += e[i]

t3 = time.time()

print( 'dsum is: ', dsum,end='\n\n')
print('Init time: ', t2-t1)
print('Dot time : ', t3 - t2)
print('Total time: ', t3-t1)

In [1]:
###########################################################################
#   Example:  In-place vs. out-of-place operations
#           
#             We can avoid unnecessary array copying, and save time,
#             by using in-place operators where possible.
#             Use a += 2 instead of a = a+2, a *=2 instead of a = a*2, etc.

import numpy as np
import time


npts = 10000000
ntrials = 4
a = np.zeros(npts)
b = np.zeros(npts)


print(' ')
print(' Timing in-place vs. out-of-place array operations')
print(' Number of elements: ', npts)
print(' Number of trials  : ', ntrials)
print('')
# This appears to be in-place, but in fact a new array is made (a*2) and reassigned to a
t0 = time.time()
for i in range(ntrials):
    a = a*2
t1 = time.time()
dt1 = t1-t0


# This is truly in-place
t0 = time.time()
for i in range(ntrials):
    a *= 2
t1 = time.time()
dt2 = t1-t0


# And here, we have a clearly out-of-place operation (a*2 is calculated and then assigned to b)
t0 = time.time()
for i in range(ntrials):
    b = a*2
t1 = time.time()
dt3 = t1-t0

tstr1 = '{:.4e}'.format(dt1)
tstr2 = '{:.4e}'.format(dt2)
tstr3 = '{:.4e}'.format(dt3)

print('   "In-place"    ( a  = a*2 ) : '+tstr1+' seconds')
print('    In-place     ( a *= 2   ) : '+tstr2+' seconds')
print('    Out-of-place ( b  = a*2 ) : '+tstr3+' seconds')







    




 
 Timing in-place vs. out-of-place array operations
 Number of elements:  10000000
 Number of trials  :  4

   "In-place"    ( a  = a*2 ) : 1.4817e-01 seconds
    In-place     ( a *= 2   ) : 6.4163e-02 seconds
    Out-of-place ( b  = a*2 ) : 1.2230e-01 seconds


In [2]:
##################################################################
#  Example:   Numpy array ordering
#             In this example, we demonstrate the difference between
#             row-major and column-major ordering of the array.
import numpy as np

dt    = 'int32'  # 4-byte integers

#Create a 1-D array with elements numbered 1 through 8
values = np.arange(1,9,1,dtype=dt)



#Reshape the 1-D array in two different ways

#Row-major ordering (default behavior; C-like).
#Values are loaded into row 0, then row 1, etc. 
array2d_row_major = np.reshape(values,(4,2),order='C')

#Column-major ordering (Fortran-like)
#Values are loaded into column 0, then column 1, etc.
array2d_col_major = np.reshape(values,(4,2),order='F')


print('')
print('values: ')
print(values)
print('')

print('2-D reshape; row-major):')
print(array2d_row_major)
print('')

print('')
print('2-D reshape; column-major):')
print(array2d_col_major)
print('')




values: 
[1 2 3 4 5 6 7 8]

2-D reshape; row-major):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


2-D reshape; column-major):
[[1 5]
 [2 6]
 [3 7]
 [4 8]]



In [3]:
####################################################################
# Example:    Numpy array access patterns
#
#             In general, try not to loop over array elements; use
#             vectorized operations whenever possible.  That said,
#             sometimes loops cannot be avoided.  When you HAVE to write a 
#             loop, the order in which you access the array can affect 
#             computation speed.  If the array is row-major (default), 
#             it is most efficient to work row-by-row.  If the array is 
#             column major, work column-by-column instead.
#
#             In this example, we perform vector dot products with
#             rows and columns of an arrays that are both row-major
#             and column-major

from time import time
import numpy as np


nx = 64
nsizes = 6
ntests = 50
orders = ['C', 'F']
otitles = [' Row Major (C-style)', 'Column Major (Fortran-style)']
print('Vector-Matrix Multiplication Timings')

for i,o in enumerate(orders):
    print(' ')
    print('Array ordering: ', otitles[i])
    for k in range(nsizes):
        nxy = nx*(2**k)
        nxys = 'nx: '+'{:4}'.format(nxy)
        
        vec = np.zeros(nxy,dtype='float64', order=o)
        mat = np.zeros((nxy,nxy),dtype='float64', order=o)

        # first pass:  vec = mat[:,j]
        t0 = time()  
        for n in range(ntests):
            for j in range(nxy):
                vec2 = mat[:,j]
                dsum = np.sum(vec2*vec)
            t1 = time()
        dt1 = (t1-t0)/ntests

        # second pass:  vec = mat[j,:]
        t0 = time()  
        for n in range(ntests):
            for j in range(nxy):
                vec2 = mat[j,:]
                dsum = np.sum(vec2*vec)
            t1 = time()

        dt2 = (t1-t0)/ntests
        s2 = 1.0/dt2
        s1 = 1.0/dt1
        ds = (s2-s1)/s1
        ds = ds*100
        dratio = dt1/dt2
        dss = '{:.4f}'.format(dratio)
        dss = '(Column-wise Time)/(Row-wise time) = '+dss
        print(nxys, ';', dss)


Vector-Matrix Multiplication Timings
 
Array ordering:   Row Major (C-style)
nx:   64 ; (Column-wise Time)/(Row-wise time) = 1.8825
nx:  128 ; (Column-wise Time)/(Row-wise time) = 1.6179
nx:  256 ; (Column-wise Time)/(Row-wise time) = 1.2168
nx:  512 ; (Column-wise Time)/(Row-wise time) = 1.1859
nx: 1024 ; (Column-wise Time)/(Row-wise time) = 1.3818
nx: 2048 ; (Column-wise Time)/(Row-wise time) = 2.4879
 
Array ordering:  Column Major (Fortran-style)
nx:   64 ; (Column-wise Time)/(Row-wise time) = 0.8656
nx:  128 ; (Column-wise Time)/(Row-wise time) = 0.7824
nx:  256 ; (Column-wise Time)/(Row-wise time) = 0.7492
nx:  512 ; (Column-wise Time)/(Row-wise time) = 0.8819
nx: 1024 ; (Column-wise Time)/(Row-wise time) = 0.8146
nx: 2048 ; (Column-wise Time)/(Row-wise time) = 0.4223


In [6]:
##################################################################################
#  Example:   Writing & reading numpy arrays
#
#             We can write array contents in unformatted binary using tofile.
#             We can read from a file using fromfile.
#
#             NOTE:   Regardless of an array's ordering, tofile will
#                     ALWAYS write the array in row-major order.
#                     To see this, change the ordering of simple_array to 'F.'
#                     array2d[a,b] and array3d will remain unchanged.

import numpy as np

ofile = 'numpy_output.dat'
dt    = 'int32'  # 4-byte integers


simple_array = np.zeros((4,2),dtype=dt)

simple_array[0,0] = 1
simple_array[0,1] = 2
simple_array[1,0] = 3
simple_array[1,1] = 4
simple_array[2,0] = 5
simple_array[2,1] = 6
simple_array[3,0] = 7
simple_array[3,1] = 8

print(simple_array)
#Writing an array is easy - just specify a filename
simple_array.tofile(ofile)

#When reading unformatted binary, we specify 
#   (1)  The filename
#   (2)  The datatype
#   (3)  The number of values to read

values = np.fromfile(ofile,dtype=dt,count=8)


#We can reshape the data as desired
array2da = np.reshape(values,(4,2),order='F')
array2db = np.reshape(values,(2,4))
array3d = np.reshape(values,(2,2,2))

print('')
print('values: ')
print(values)
print('')

print('2-D array; 4 rows, 2 columns):')
print(array2da)
print('')

print('')
print('2-D array; 2 rows, 4 columns):')
print(array2db)
print('')

print('')
print('3-D array:')
print(array3d)
print('')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

values: 
[1 2 3 4 5 6 7 8]

2-D array; 4 rows, 2 columns):
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


2-D array; 2 rows, 4 columns):
[[1 2 3 4]
 [5 6 7 8]]


3-D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [14]:
import numpy as np
#Write the number 769 out to disk in native Endianness
my_number = np.zeros(1,dtype='int16')
my_number[0]=769
my_number.tofile('769.dat')

big_num = np.fromfile('769_big.dat',dtype='int16',count=1)

In [9]:
print(my_number)

[769]


In [15]:
print(big_num)

[259]
